###

GET http://localhost:3011/


###

POST http://localhost:3011/users
Content-Type: application/json


{
    "name":"deva",
    "email":"deva@gmail.com",
    "imageurl":"http://image1.png"
}



###

PUT http://localhost:3011/users/2
Content-Type: application/json


{
    "name":"deva",
    "email":"deva1@gmail.com",
    "imageurl":"http://image1.png"
}



###

DELETE http://localhost:3011/users/2